# Generated by Django 3.1.5 on 2021-01-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210114_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='URL',
            field=models.URLField(default=0),
        ),
    ]
