# Generated by Django 3.2 on 2021-04-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='git_URL',
            field=models.URLField(default=0),
        ),
    ]
